version: '3.8'

volumes:
  db-data:
  queue-data:
  queue-log:

networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: docker/nginx
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf:cached
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - dev
  php-fpm:
    build:
      context: docker/php
    restart: on-failure
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - mysql
    networks:
      - dev
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - dev
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queue-data:/var/lib/rabbitmq/
      - queue-log:/var/log/rabbitmq
    networks:
      - dev
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - dev
